export const OrderCreateErrorEnum = {
  OrderCreateBlockedByKYT: "order_create_blocked_by_kyt",
  CountryDisabled: "country_disabled",
  CurrencyDisabled: "currency_disabled",
  InvalidCurrencyIso: "invalid_currency_iso",
  CryptoAssetDisabled: "crypto_asset_disabled",
  InvalidCryptoAssetCode: "invalid_crypto_asset_code",
  InvalidWallet: "invalid_wallet",
  InvalidUserId: "invalid_user_id",
  UserNotFound: "user_not_found",
  InvalidPaymentMethod: "invalid_payment_method",
  MethodCurrencyDisabled: "method_currency_disabled",
  FiatMinLimit: "fiat_min_limit",
  FiatMaxLimit: "fiat_max_limit",
  ReachedMaxLimitByKyc: "reached_max_limit_by_kyc",
  CryptoMinLimit: "crypto_min_limit",
  CryptoMaxLimit: "crypto_max_limit",
  ProcessingFeeWasChanged: "processing_fee_was_changed",
  NetworkFeeWasChanged: "network_fee_was_changed",
  RatesChangedLot: "rates_changed_lot",
}

export enum OrderCreateErrorEnumV2 {
  OrderCreateBlockedByKYT = "order_create_blocked_by_kyt",
  CountryDisabled = "country_disabled",
  CurrencyDisabled = "currency_disabled",
  InvalidCurrencyIso = "invalid_currency_iso",
  CryptoAssetDisabled = "crypto_asset_disabled",
  InvalidCryptoAssetCode = "invalid_crypto_asset_code",
  InvalidWallet = "invalid_wallet",
  InvalidUserId = "invalid_user_id",
  UserNotFound = "user_not_found",
  InvalidPaymentMethod = "invalid_payment_method",
  MethodCurrencyDisabled = "method_currency_disabled",
  FiatMinLimit = "fiat_min_limit",
  FiatMaxLimit = "fiat_max_limit",
  CryptoMinLimit = "crypto_min_limit",
  CryptoMaxLimit = "crypto_max_limit",
  ReachedMaxLimitByKyc = "reached_max_limit_by_kyc",
  ProcessingFeeWasChanged = "processing_fee_was_changed",
  NetworkFeeWasChanged = "network_fee_was_changed",
  RatesChangedLot = "rates_changed_lot",
}
